# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sniffer_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BeginButton = QtWidgets.QPushButton(self.centralwidget)
        self.BeginButton.setGeometry(QtCore.QRect(30, 20, 101, 31))
        self.BeginButton.setObjectName("BeginButton")
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setEnabled(False)
        self.StopButton.setGeometry(QtCore.QRect(140, 20, 101, 31))
        self.StopButton.setObjectName("StopButton")
        self.ResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResetButton.setGeometry(QtCore.QRect(250, 20, 101, 31))
        self.ResetButton.setObjectName("ResetButton")
        self.FilterBox = QtWidgets.QComboBox(self.centralwidget)
        self.FilterBox.setGeometry(QtCore.QRect(530, 20, 71, 31))
        self.FilterBox.setObjectName("FilterBox")
        self.NICBox = QtWidgets.QComboBox(self.centralwidget)
        self.NICBox.setGeometry(QtCore.QRect(140, 80, 621, 41))
        self.NICBox.setObjectName("NICBox")
        self.PacketTable = QtWidgets.QTableWidget(self.centralwidget)
        self.PacketTable.setGeometry(QtCore.QRect(40, 140, 731, 251))
        self.PacketTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.PacketTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.PacketTable.setColumnCount(4)
        self.PacketTable.setObjectName("PacketTable")
        self.PacketTable.setRowCount(0)
        self.PacketInfoText = QtWidgets.QTextEdit(self.centralwidget)
        self.PacketInfoText.setGeometry(QtCore.QRect(40, 400, 211, 161))
        self.PacketInfoText.setObjectName("PacketInfoText")
        self.PacketHexText = QtWidgets.QTextEdit(self.centralwidget)
        self.PacketHexText.setGeometry(QtCore.QRect(270, 400, 501, 161))
        self.PacketHexText.setObjectName("PacketHexText")
        self.FilterDIY = QtWidgets.QLineEdit(self.centralwidget)
        self.FilterDIY.setGeometry(QtCore.QRect(620, 20, 171, 31))
        self.FilterDIY.setObjectName("FilterDIY")
        self.FilterText = QtWidgets.QLabel(self.centralwidget)
        self.FilterText.setGeometry(QtCore.QRect(390, 10, 131, 51))
        self.FilterText.setObjectName("FilterText")
        self.NICText = QtWidgets.QLabel(self.centralwidget)
        self.NICText.setGeometry(QtCore.QRect(70, 90, 101, 31))
        self.NICText.setObjectName("NICText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NaiveSniffer"))
        self.BeginButton.setText(_translate("MainWindow", "Begin"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.ResetButton.setText(_translate("MainWindow", "Reset"))
        self.FilterText.setText(_translate("MainWindow", "Filter:(Options/BPF)"))
        self.NICText.setText(_translate("MainWindow", "Adapter:"))
